// This file was auto-generated by ML.NET Model Builder. 

using System;
using MLTestML.Model;

namespace MLTestML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Code = @"int a; ",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Malicious with predicted Malicious from sample data...\n\n");
            Console.WriteLine($"Code: {sampleData.Code}");
            Console.WriteLine($"\n\nPredicted Malicious value {predictionResult.Prediction} \nPredicted Malicious scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
